### ISSUE TITLE
Can I incorporate your code into another project?

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [alexdotis/Chibisafe-Sharex-Scraper#1]
Hey there! 

I maintain a project quite similar to yours and I wanted to reach out to see if you'd have any problems with me incorporating your code base into my project.

**Comment by ItsDrike** [comment]
Hi @Jules-WinnfieldX, thanks for asking! You absolutely can utilize the code here in any project you like, but there are some legal guidelines to follow. 

This project is licensed under GPL v3, which is a copy-left license. This means that for you to be able to use parts of this code-base in another project, that project is also required to be licensed under GPL v3 (I assume it's [this](https://github.com/Jules-WinnfieldX/CyberDropDownloader) project though, which means it already is under the same lincese). Just know that at any point, you can not relicense your project under anything non-GPL v3 compatible as long as you will still have parts of this code-base utilized in yours.

Another requirement of the license is to give proper attribution to the original source. You can do this in multiple ways, for example if you intent to make a fork, you don't need to worry about this at all since github already shows that your repo is a fork comming from this original repository. However since you already have a repo, you will need to explicitly mention it somewhere in it. The most common location to do this would be the `README` file, however if you don't want to clutter it with attributions, you can also make `LICENSE-THIRD-PARTY` file in your repositry, which should include exactly which parts of your code-base are comming from this project (or, if you're going to be taking large portions of the code, essentially turning your project into a fork, you will want to mention that the project was based/forked from this one), and a link back to this project.

The GPL license also requires you to state the changes between the original project and a fork, however if you only intent to use some parts of this code-base, you obviously don't need to state that you've changed everything except x. This is only really relevant if you wanted to re-use significant chunks of the code-base, making your project essentially a fork of this one. To do this, you can keep a `CHANGELOG` file, listing the differences.

Good luck with your project!
